/**
 * @file deploy plugin — pure SHA-pinned GitHub Actions workflow generator.
 */
import { MOKU_WRANGLER_VERSION } from "../wrangler";

/** Pinned `actions/checkout` commit SHA (with its release tag for auditing). */
const CHECKOUT_SHA = "11bd71901bbe5b1630ceea73d27597364c9af683"; // v4.2.2

/** Pinned `oven-sh/setup-bun` commit SHA. */
const SETUP_BUN_SHA = "4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5"; // v2.0.1

/** Pinned `cloudflare/wrangler-action` commit SHA. */
const WRANGLER_ACTION_SHA = "f84a562284fc78278ff9052435d9526f9c718361"; // v4.0.0

/**
 * What triggers the generated deploy workflow:
 * - `"auto"` — every push to `main` (plus the manual "Run workflow" button).
 * - `"versioned-tag"` — pushing a `v*` semver tag (plus the manual button).
 * - `"dispatch"` — only the manual "Run workflow" button (no automation).
 *
 * @example
 * const trigger: WorkflowTrigger = "versioned-tag";
 */
export type WorkflowTrigger = "auto" | "versioned-tag" | "dispatch";

/** The `on:` block for each {@link WorkflowTrigger} (kept indentation-exact for YAML). */
const TRIGGER_ON_BLOCKS: Record<WorkflowTrigger, string> = {
  auto: `on:
  push:
    branches: [main]
  workflow_dispatch:`,
  "versioned-tag": `on:
  push:
    tags: ["v*"]
  workflow_dispatch:`,
  dispatch: `on:
  workflow_dispatch:`
};

/**
 * Generate a SHA-pinned GitHub Actions workflow that builds and deploys to
 * Cloudflare Pages. Every action is pinned to a commit SHA (with a `# vX`
 * comment) rather than a floating tag, and the wrangler version comes from the
 * single {@link MOKU_WRANGLER_VERSION} source of truth so generated and deployed
 * versions cannot drift. Secrets are injected via `${{ secrets.* }}`, never inlined.
 *
 * @param input - The generator inputs.
 * @param input.slug - Cloudflare project-name slug used as the wrangler `--project-name`.
 * @param input.trigger - What fires the workflow (see {@link WorkflowTrigger}). Default `"auto"`.
 * @returns The workflow YAML.
 * @example
 * generateGithubWorkflow({ slug: "my-site", trigger: "versioned-tag" });
 */
export function generateGithubWorkflow(input: { slug: string; trigger?: WorkflowTrigger }): string {
  const onBlock = TRIGGER_ON_BLOCKS[input.trigger ?? "auto"];
  return `# .github/workflows/deploy.yml — generated by \`app.deploy.init({ ci: true })\`.
# Actions are SHA-pinned (not floating tags) for supply-chain hygiene.

name: Deploy

${onBlock}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@${CHECKOUT_SHA} # v4.2.2
      - uses: oven-sh/setup-bun@${SETUP_BUN_SHA} # v2.0.1
      - run: bun install --frozen-lockfile
      - run: bun run build
      - uses: cloudflare/wrangler-action@${WRANGLER_ACTION_SHA} # v4.0.0
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "${MOKU_WRANGLER_VERSION}"
          command: pages deploy dist --project-name ${input.slug}
`;
}
